#!/usr/bin/env bash
# silzy.nvim installer
# Usage: curl -fsSL https://raw.githubusercontent.com/yourusername/silzy.nvim/main/scripts/install.sh | bash

set -euo pipefail

# ─── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[1;33m'
BLU='\033[0;34m'
BLD='\033[1m'
RST='\033[0m'

info()    { echo -e "${BLU}[silzy]${RST} $*"; }
success() { echo -e "${GRN}[silzy] ✓${RST} $*"; }
warn()    { echo -e "${YLW}[silzy] !${RST} $*"; }
error()   { echo -e "${RED}[silzy] ✗${RST} $*" >&2; exit 1; }

# ─── Banner ───────────────────────────────────────────────────────────────────
echo -e "${BLD}"
cat <<'EOF'
  ███████╗██╗██╗     ███████╗██╗   ██╗   ███╗   ██╗██╗   ██╗██╗███╗   ███╗
  ██╔════╝██║██║     ╚════██║╚██╗ ██╔╝   ████╗  ██║██║   ██║██║████╗ ████║
  ███████╗██║██║         ██╔╝  ╚████╔╝    ██╔██╗ ██║██║   ██║██║██╔████╔██║
  ╚════██║██║██║        ██╔╝    ╚██╔╝     ██║╚██╗██║╚██╗ ██╔╝██║██║╚██╔╝██║
  ███████║██║███████╗   ██║      ██║      ██║ ╚████║ ╚████╔╝ ██║██║ ╚═╝ ██║
  ╚══════╝╚═╝╚══════╝   ╚═╝      ╚═╝      ╚═╝  ╚═══╝  ╚═══╝  ╚═╝╚═╝     ╚═╝
                         Neovim Package Manager
EOF
echo -e "${RST}"

# ─── Prerequisites ────────────────────────────────────────────────────────────
command -v nvim &>/dev/null  || error "Neovim is not installed. Install it first: https://neovim.io"
command -v git  &>/dev/null  || error "git is not installed."

NVIM_VERSION=$(nvim --version | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "0.0.0")
NVIM_MAJOR=$(echo "$NVIM_VERSION" | cut -d. -f1)
NVIM_MINOR=$(echo "$NVIM_VERSION" | cut -d. -f2)

if [[ $NVIM_MAJOR -lt 1 && $NVIM_MINOR -lt 9 ]]; then
  error "silzy.nvim requires Neovim ≥ 0.9.0 (found $NVIM_VERSION)"
fi
info "Neovim $NVIM_VERSION detected — OK"

# ─── Paths ────────────────────────────────────────────────────────────────────
NVIM_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
SILZY_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/silzy"
SILZY_MANAGER_DIR="$SILZY_DATA_DIR/manager"
REPO_URL="https://github.com/yourusername/silzy.nvim.git"

# ─── Backup existing config ───────────────────────────────────────────────────
if [[ -d "$NVIM_CONFIG_DIR" ]]; then
  BACKUP_DIR="${NVIM_CONFIG_DIR}.bak.$(date +%Y%m%d_%H%M%S)"
  warn "Existing Neovim config found. Backing up to: $BACKUP_DIR"
  mv "$NVIM_CONFIG_DIR" "$BACKUP_DIR"
  success "Backup created at $BACKUP_DIR"
fi

# ─── Clone silzy.nvim ─────────────────────────────────────────────────────────
info "Cloning silzy.nvim..."
mkdir -p "$SILZY_DATA_DIR"
git clone --depth=1 --filter=blob:none "$REPO_URL" "$SILZY_MANAGER_DIR" \
  || error "Failed to clone silzy.nvim from $REPO_URL"
success "silzy.nvim cloned to $SILZY_MANAGER_DIR"

# ─── Create nvim config directory ─────────────────────────────────────────────
info "Setting up Neovim config at $NVIM_CONFIG_DIR..."
mkdir -p "$NVIM_CONFIG_DIR/lua/core/plugins"
mkdir -p "$NVIM_CONFIG_DIR/lua/config"

# ─── Write init.lua ───────────────────────────────────────────────────────────
cat > "$NVIM_CONFIG_DIR/init.lua" <<'INIT_LUA'
-- Generated by silzy.nvim installer
-- Bootstrap silzy.nvim
local silzy_path = vim.fn.stdpath("data") .. "/silzy/manager"
if vim.fn.empty(vim.fn.glob(silzy_path)) > 0 then
  vim.fn.system({
    "git", "clone", "--depth=1", "--filter=blob:none",
    "https://github.com/yourusername/silzy.nvim.git",
    silzy_path,
  })
end
vim.opt.runtimepath:prepend(silzy_path)

require("config.options")
require("config.keymaps")

local silzy = require("silzy")
silzy.setup({ auto_install = true })

require("core")
INIT_LUA

# ─── Copy starter configs ─────────────────────────────────────────────────────
# Copy bundled config files from the manager repo
cp "$SILZY_MANAGER_DIR/lua/config/options.lua" "$NVIM_CONFIG_DIR/lua/config/options.lua"
cp "$SILZY_MANAGER_DIR/lua/config/keymaps.lua" "$NVIM_CONFIG_DIR/lua/config/keymaps.lua"
cp "$SILZY_MANAGER_DIR/lua/core/init.lua"       "$NVIM_CONFIG_DIR/lua/core/init.lua"

# Copy bundled core plugins (snacks, telescope, neotree)
for f in "$SILZY_MANAGER_DIR/lua/core/plugins/"*.lua; do
  cp "$f" "$NVIM_CONFIG_DIR/lua/core/plugins/"
done

success "Neovim config written."

# ─── Optional: recommend fd & ripgrep ─────────────────────────────────────────
echo ""
info "Recommended external tools for best experience:"
echo "  • fd         (faster file finding)   — https://github.com/sharkdp/fd"
echo "  • ripgrep    (live grep)              — https://github.com/BurntSushi/ripgrep"
echo "  • lazygit    (git TUI)                — https://github.com/jesseduffield/lazygit"
echo "  • nerd-fonts (icons in file tree)     — https://www.nerdfonts.com"
echo ""

# ─── Done ─────────────────────────────────────────────────────────────────────
success "silzy.nvim installation complete!"
echo ""
echo -e "  ${BLD}Next step:${RST} Open Neovim with ${GRN}nvim${RST}"
echo -e "  The first-run wizard will appear automatically."
echo ""
